### ISSUE TITLE
Multiple locks - Setup as 'platform' instead of 'accessory'

### ISSUE THREAD

**Issue by luciengaitskell** [quacktacular/homebridge-qsesame#1]
I have had issues setting up multiple sesames as individual accessories. When controlling one Lock device in HomeKit, it causes the other device to change too, and show the same state. If you are supposed to be able to setup multiple locks, this must be a bug.

Thanks

**Comment by quacktacular** [comment]
This version is meant to operate as an accessory only. For multiple locks you'd have to setup multiple accessories separately. I plan to write a platform version eventually.
