### ISSUE TITLE
Bluetooth 

### ISSUE THREAD

**Issue by samsonrosen** [quacktacular/homebridge-qsesame#2]
Hi,

Do you have any plans to integrate the plugin with:

https://www.npmjs.com/package/homebridge-bluetooth

I feel this would avoid the wifi adapter or the virtual station app. I don't know if you can control the Sesame via API though.

**Comment by quacktacular** [comment]
I would love this!!! CANDYHOUSE, however, has not released a Bluetooth API. So it isn't currently possible :(
