### ISSUE TITLE
Homekit shows lock/unlock but does not actually turn the lock

### ISSUE THREAD

**Issue by zelik888** [quacktacular/homebridge-qsesame#3]
Strange, the lock intermittently worked with homekit but now it completely doesn't turn when triggered from homekit. I am trying to figure out how to debug it. Everything works with the virtual AP if I use the Sesame app over Wifi w/o bluetooth. The API is on and IFTT works. 

Any clues on how to debug this?

**Comment by quacktacular** [comment]
Hmmm there has been some strangeness with the API lately. What response do you see in in the home bridge output when you request lock state change?

**Comment by zelik888** [comment]
This was a problem with Sesame's API. It's now fixed, closing. Thank you. Lock state is, as stated, erratic but that's how it always has been.
